#!/bin.sh

#cleanup

rm -rf obj_dir
rm -f reg_alu_top.vcd

#run Verilator to trasnlate Verilof into C++ inc testbench
verilator -Wall --cc --trace reg_alu_top.sv alu.sv regfile.sv --exe reg_alu_top_tb.cpp

#build C++ via make, autogenerated by Verilator
make -j -C obj_dir -f Vreg_alu_top.mk Vreg_alu_top

#run executable 
obj_dir/Vreg_alu_top

