#!/bin/sh

cd ./Instr

# cleanup
rm -rf ob_dir
rm -f test1.vcd

# run verilator to translate Verilog into C++, including C++ test bench
verilator -Wall --cc --trace Instr.sv --exe Instr_test_tb.cpp > /dev/null

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VInstr.mk VPC > /dev/null

# run executable simulation file
obj_dir/VInstr