#!/bin/sh

# cleanup
rm -rf ob_dir
rm -f PCReg.vcd

# run verilator to translate Verilog into C++, including C++ test bench
verilator -Wall --cc --trace PCReg.sv --exe PCReg_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VPCReg.mk VPCReg

# run executable simulation file
obj_dir/VPCReg