#!/bin/bash

# Run unit tests stored within each module's folder

tests=$(find | grep tests.sh -w)
tests=(`echo $tests | tr '\n' ' '`)

echo "===== TESTING SUITE ====="
echo "No of tests found: ${#tests[@]}"

failed=false

for test in $tests
do
    result=$(sh $test)
    if [ "$result" != "[PASS]" ]
    then
        echo "FAILED ON $test"
        echo "$result"
        failed=true
    fi
done
if [ !failed ] 
then
    echo "ALL UNIT TESTS PASSED"
fi

# if $f

# # Run comined test

# rm -rf ob_dir
# rm -f top.vcd

# # run verilator to translate Verilog into C++, including C++ test bench
# verilator -Wall --cc --trace PC.sv --exe top_tb.cpp

# # build C++ project via make automatically generated by Verilator
# make -j -C obj_dir/ -f Vtop.mk Vtop

# obj_dir/Vtop