#!/bin/sh

# cleanup
rm -rf ob_dir
rm -f PC.vcd

# run verilator to translate Verilog into C++, including C++ test bench
verilator -Wall --cc --trace PC.sv --exe PC_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VPC.mk VPC

# run executable simulation file
obj_dir/VPC