#!/bin/sh

cd ./PC

# cleanup
rm -rf ob_dir
rm -f test1.vcd
rm -f test2.vcd

# run verilator to translate Verilog into C++, including C++ test bench
verilator -Wall --cc --trace PC.sv --exe PC_test_tb.cpp > /dev/null

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VPC.mk VPC > /dev/null

# run executable simulation file
obj_dir/VPC